### ISSUE TITLE
Cache issue and 404's

### ISSUE THREAD

**Issue by mdcooper** [saucecontrol/PhotoSauce#57] opened 2020-10-12 19:22 UTC
Occasionally we're seeing 404s returned on all or nearly all image requests. These images should already be in the disk cache. If I delete the cache folders the images will appear once and then return to 404's for the next request. I'm guessing we might have some config issues. We are currently using option 2 where we register the module explicitly in the system.webServer section of the web.config.

One side note - the cached image files are all named like _3YR3JXXCᨾ跑�.IMG_1481.600x450.JPG_ is that an expected character set for naming strategy? I'm not sure if that is related to the 404s, but figured I would mention that.

Thanks!

**Comment by saucecontrol** [comment] 2020-10-12 19:57
Yeah, seems likely the extra characters in the file name would be the cause.  I saw that happen once in one of my deployments, but it was over a year (and a couple of release versions) ago and only happened once.  I don't remember identifying the cause, so it could still be there.

Just looking at the code now, I see a potential bug in that the string for the hash should be null terminated and isn't.  I'll push an update to that in a bit.

Would you be able to try out a CI build to see if that fixes it up?

**Comment by saucecontrol** [comment] 2020-10-13 05:57
I pushed a fix up if you want to give it a try.  You'll need both the [MagicScaler](https://dev.azure.com/saucecontrol/PhotoSauce/_packaging?_a=package&feed=photosauce_ci%40Local&package=PhotoSauce.MagicScaler&version=0.11.2-ci202861&protocolType=NuGet) and [WebRSize](https://dev.azure.com/saucecontrol/PhotoSauce/_packaging?_a=package&feed=photosauce_ci%40Local&package=PhotoSauce.WebRSize&version=0.6.2-ci202861&protocolType=NuGet) packages from CI

**Comment by saucecontrol** [comment] 2020-11-04 08:09
New release is up that should fix this.

**Closed by saucecontrol** 2020-11-04 08:09 UTC
