### ISSUE TITLE
ArgumentException when NearestNeighbor and scale-down

### ISSUE THREAD

**Issue by neelabo** [saucecontrol/PhotoSauce#7] opened 2017-07-31 13:29 UTC
System.ArgumentException "Value does not fall within the expected range."
when NearestNeighbor and scale-down, maybe.

* version: MagicScaler 0.8.0-beta3

* StackTrace

<pre>
   at PhotoSauce.MagicScaler.Interop.IWICBitmapFrameEncode.WriteSource(IWICBitmapSource pIBitmapSource, WICRect prc)
   at PhotoSauce.MagicScaler.WicEncoder.WriteSource(WicProcessingContext ctx) in C:\gitlocal\photosauce\src\MagicScaler\WIC\WicCodec.cs:line 166
   at PhotoSauce.MagicScaler.MagicImageProcessor.executePipeline(WicProcessingContext ctx, Stream ostm) in C:\gitlocal\photosauce\src\MagicScaler\Magic\MagicImageProcessor.cs:line 193
   at PhotoSauce.MagicScaler.MagicImageProcessor.ProcessImage(Stream imgStream, Stream outStream, ProcessImageSettings settings) in C:\gitlocal\photosauce\src\MagicScaler\Magic\MagicImageProcessor.cs:line 61
</pre>

* sample code 

<pre>
    // For example, inStream is #6 issue's picture.
    var setting = new ProcessImageSettings();
    setting.Width = 64;
    setting.Height = 64;
    setting.Interpolation = InterpolationSettings.NearestNeighbor;
    MagicImageProcessor.ProcessImage(inStream, outStream, setting); 
</pre>

**Comment by saucecontrol** [comment] 2017-07-31 23:18
That error is caused by a bad interaction between the planar pipeline's cache (because your source image is a JPEG) and the scaler, because point sampling doesn't consume all the input pixels.  It's not a scenario I have covered in my tests because it's really not intended to be used that way.  I'd recommend against using nearest neighbor interpolation when downscaling images in general, and particularly when downscaling JPEG images.  The sample image you provided in #6 was a prime example of misuse of the JPEG format, so the whole scenario is a bit strange.

I'll get the planar cache fixed up so it can't error in situations like this, but I don't have time to look at it for a few days.  For now you can either disable planar mode (`MagicImageProcessor.EnablePlanarPipeline = false`) or use a high-quality interpolator.

**Comment by neelabo** [comment] 2017-08-01 01:53
(I am using Google Translate. I am sorry if the grammar is strange.)

As a precaution, I will report that similar phenomena are occurring in many JPEG other than sample images used in #6.

I have confirmed that the phenomenon will not occur in the way you suggested, so I will adopt this method for the time being.

Thank you.

**Comment by saucecontrol** [comment] 2017-08-01 06:53
Wow, google translate is doing a great job :)

This problem will occur with any YCbrCr JPEG as long as the scaling ratio is less than 8:1.  The problem is that the planar cache tracks the pixels consumed from each plane by incrementing a counter each time a line is read.  The nearest neighbor interpolator doesn't sample all lines, so the counter doesn't keep an accurate position within the cache.  It's not a difficult fix, just not an expected use-case.  I appreciate your bug report, and I'll get a fix done shortly.

**Comment by saucecontrol** [comment] 2017-08-31 05:06
Fixed in 6b72c16ea379dd4f7e7ac37039b61ef10284ae29

**Closed by saucecontrol** 2017-08-31 05:06 UTC
